include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    # strict-raw-types: true
  # errors:
  #   invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - build/**
  plugins:
    - custom_lint

linter:
  rules:
    prefer_single_quotes: true
    cancel_subscriptions: true
