name: portfolio

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# ignore: sort_pub_dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # http
  http: ^1.2.2 # client interface
  cronet_http: ^1.3.2 # android client
  fetch_client: ^1.1.2 # browser client
  cupertino_http: ^1.5.1 # apple client

  # model specifics
  crypto: ^3.0.3
  convert: ^3.1.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  # platform UI
  yaru: ^4.0.0
  macos_ui: ^2.0.7
  fluent_ui: ^4.9.1
  system_theme: ^3.0.0
  cupertino_icons: ^1.0.6

  # state, locator and logger
  get_it: ^7.7.0
  go_router: ^14.2.3
  talker_flutter: ^4.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  talker_riverpod_logger: ^4.4.0

  # storage and sharing
  hive: ^4.0.0-dev.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  isar_flutter_libs: ^4.0.0-dev.13
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
  # assets:
  # - assets/test
