// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;
import 'package:portfolio/src/common/const.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (KPlatform.isWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-5pjDmqD9YZmtDKw-8iWnZjdOhPKT3U',
    appId: '1:400437740389:web:6b9456c5cb7df97447978c',
    messagingSenderId: '400437740389',
    projectId: 'atumra-portfolio-6fb12',
    authDomain: 'atumra-portfolio-6fb12.firebaseapp.com',
    storageBucket: 'atumra-portfolio-6fb12.appspot.com',
    measurementId: 'G-PWF8X5MDZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtASyL6__ErnceZV_tLtzjIWrK_ldNUBY',
    appId: '1:400437740389:android:3a1b62d96c6b01b047978c',
    messagingSenderId: '400437740389',
    projectId: 'atumra-portfolio-6fb12',
    storageBucket: 'atumra-portfolio-6fb12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUuCW_dmcSPLKNFw8Y7MqQti-PgSSCaOY',
    appId: '1:400437740389:ios:241b2e24a2009f1547978c',
    messagingSenderId: '400437740389',
    projectId: 'atumra-portfolio-6fb12',
    storageBucket: 'atumra-portfolio-6fb12.appspot.com',
    iosBundleId: 'com.atumra.portfolio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUuCW_dmcSPLKNFw8Y7MqQti-PgSSCaOY',
    appId: '1:400437740389:ios:241b2e24a2009f1547978c',
    messagingSenderId: '400437740389',
    projectId: 'atumra-portfolio-6fb12',
    storageBucket: 'atumra-portfolio-6fb12.appspot.com',
    iosBundleId: 'com.atumra.portfolio.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-5pjDmqD9YZmtDKw-8iWnZjdOhPKT3U',
    appId: '1:400437740389:web:2cc232d5d775ee6347978c',
    messagingSenderId: '400437740389',
    projectId: 'atumra-portfolio-6fb12',
    authDomain: 'atumra-portfolio-6fb12.firebaseapp.com',
    storageBucket: 'atumra-portfolio-6fb12.appspot.com',
    measurementId: 'G-Q307R6MMHK',
  );

}