// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;
import 'package:portfolio/src/common/const.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Const.isWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2WcddTEAKZIllW6bJ9V01UdOtXxcn_c',
    appId: '1:814750292363:web:3cda9fc83245f57659f78e',
    messagingSenderId: '814750292363',
    projectId: 'atumra-portfolio',
    authDomain: 'atumra-portfolio.firebaseapp.com',
    storageBucket: 'atumra-portfolio.appspot.com',
    measurementId: 'G-6TP3HRM412',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1104VrLezsbsAkVuwgExWv5YFpVYBPnc',
    appId: '1:814750292363:android:2bcfe7c89530245a59f78e',
    messagingSenderId: '814750292363',
    projectId: 'atumra-portfolio',
    storageBucket: 'atumra-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhHYfBYcxlg1pR8ZgnjMdtLHk40P4sJY',
    appId: '1:814750292363:ios:b314490cd5d4344e59f78e',
    messagingSenderId: '814750292363',
    projectId: 'atumra-portfolio',
    storageBucket: 'atumra-portfolio.appspot.com',
    iosBundleId: 'com.atumra.portfolio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhHYfBYcxlg1pR8ZgnjMdtLHk40P4sJY',
    appId: '1:814750292363:ios:b314490cd5d4344e59f78e',
    messagingSenderId: '814750292363',
    projectId: 'atumra-portfolio',
    storageBucket: 'atumra-portfolio.appspot.com',
    iosBundleId: 'com.atumra.portfolio.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq2WcddTEAKZIllW6bJ9V01UdOtXxcn_c',
    appId: '1:814750292363:web:4a95ecba253eee3159f78e',
    messagingSenderId: '814750292363',
    projectId: 'atumra-portfolio',
    authDomain: 'atumra-portfolio.firebaseapp.com',
    storageBucket: 'atumra-portfolio.appspot.com',
    measurementId: 'G-Y2JL4MZVCY',
  );
}
